sudo: false

language: python

dist: xenial

python:
  - 3.5.6
  - 3.6.7
  - 3.7.0


install:
  # Install anaconda
#  - sudo apt-get update # takes 8s
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda --version
#  - conda update -q conda # takes 12s

  # Create environment
  - conda create -q -n codebase python=$TRAVIS_PYTHON_VERSION
  - conda env update -q -n codebase -f python/conda.yaml
  - source activate codebase
  - pip list
  - python --version

script:
  - pytest python/test/pytest*
  - python python/test/unittest_fixtures.py
  - pytest python --doctest-modules --continue-on-collection-errors
